apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopverse.fullname" . }}-frontend
  labels:
    {{- include "shopverse.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "shopverse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
      protocol: TCP
  selector:
    {{- include "shopverse.selectorLabels" . | nindent 4 }}
