apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopverse.fullname" . }}-headless
  labels:
    {{- include "shopverse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "shopverse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306