apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    environment: {{ .Values.env | default "production" | quote }}
