apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopverse.fullname" . }}-secrets
  labels:
    {{- include "shopverse.labels" . | nindent 4 }}
type: Opaque
data:
  mysql_root_pass: {{ .Values.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  mysql_database: {{ .Values.MYSQL_DATABASE | b64enc | quote }}
  mysql_user: {{ .Values.MYSQL_USER| b64enc | quote }}
  mysql_pass: {{ .Values.MYSQL_PASSWORD | b64enc | quote }}
  db_host: {{ .Values.DB_HOST | b64enc | quote }}
  db_port: {{ .Values.DB_PORT | b64enc | quote }}
  db_name: {{ .Values.DB_NAME | b64enc | quote }}
  db_user: {{ .Values.DB_USER | b64enc | quote }}
  db_pass: {{ .Values.DB_PASSWORD | b64enc | quote }}
  jwt_secret: {{ .Values.JWT_SECRET | b64enc | quote }}